-- MySQL Script generated by MySQL Workbench
-- Wed May 21 15:04:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema setec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema setec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `setec` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `setec` ;

-- -----------------------------------------------------
-- Table `setec`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setec`.`event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `startAt` DATETIME NULL DEFAULT NULL,
  `endAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `setec`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setec`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `role` TINYINT NOT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `relationship` TINYINT NOT NULL,
  `ra` VARCHAR(20) NULL DEFAULT NULL,
  `uid` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `setec`.`type_activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setec`.`type_activity` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `typeActivity` VARCHAR(100) NULL DEFAULT NULL,
  `needsSubscription` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `setec`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setec`.`activity` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `id_typeActivity` BIGINT NULL DEFAULT NULL,
  `activityDate` DATE NULL DEFAULT NULL,
  `fk_Event` BIGINT NOT NULL,
  `fk_admin_approved` VARCHAR(255) NULL DEFAULT NULL,
  `fk_type_activity` BIGINT NOT NULL,
  `daysQuantity` INT NULL DEFAULT NULL,
  `hoursQuantity` INT NULL DEFAULT NULL,
  `qtdeVagas` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Event` (`fk_Event` ASC) VISIBLE,
  INDEX `fk_User` (`fk_admin_approved` ASC) VISIBLE,
  INDEX `fk_type_activity` (`fk_type_activity` ASC) VISIBLE,
  CONSTRAINT `activity_ibfk_1`
    FOREIGN KEY (`fk_Event`)
    REFERENCES `setec`.`event` (`id`),
  CONSTRAINT `activity_ibfk_2`
    FOREIGN KEY (`fk_admin_approved`)
    REFERENCES `setec`.`user` (`uid`),
  CONSTRAINT `activity_ibfk_3`
    FOREIGN KEY (`fk_type_activity`)
    REFERENCES `setec`.`type_activity` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `setec`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setec`.`subscription` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `subscriptionStatus` VARCHAR(50) NULL,
  `fk_Activity` BIGINT NOT NULL,
  `fk_User` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Activity` (`fk_Activity` ASC) VISIBLE,
  INDEX `fk_User` (`fk_User` ASC) VISIBLE,
  CONSTRAINT `subscription_ibfk_1`
    FOREIGN KEY (`fk_Activity`)
    REFERENCES `setec`.`activity` (`id`),
  CONSTRAINT `subscription_ibfk_2`
    FOREIGN KEY (`fk_User`)
    REFERENCES `setec`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `setec`.`dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setec`.`dates` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT NULL,
  `fk_activity` BIGINT NOT NULL,
  `initialHour` TIME NULL DEFAULT NULL,
  `finalHour` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activity` (`fk_activity` ASC) VISIBLE,
  CONSTRAINT `dates_ibfk_1`
    FOREIGN KEY (`fk_activity`)
    REFERENCES `setec`.`activity` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `setec`.`attend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setec`.`attend` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `fk_id_subscription` BIGINT NULL DEFAULT NULL,
  `fk_date` BIGINT NOT NULL,
  `fk_user` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_subscription` (`fk_id_subscription` ASC) VISIBLE,
  INDEX `fk_date` (`fk_date` ASC) VISIBLE,
  INDEX `fk_user` (`fk_user` ASC) VISIBLE,
  CONSTRAINT `attend_ibfk_1`
    FOREIGN KEY (`fk_id_subscription`)
    REFERENCES `setec`.`subscription` (`id`),
  CONSTRAINT `attend_ibfk_2`
    FOREIGN KEY (`fk_date`)
    REFERENCES `setec`.`dates` (`id`),
  CONSTRAINT `attend_ibfk_3`
    FOREIGN KEY (`fk_user`)
    REFERENCES `setec`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `setec`.`commission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setec`.`commission` (
  `fk_Event_id_event` BIGINT NOT NULL,
  `fk_id_user` BIGINT NOT NULL,
  `id` BIGINT NOT NULL,
  INDEX `fk_id_user` (`fk_id_user` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `commission_ibfk_1`
    FOREIGN KEY (`fk_Event_id_event`)
    REFERENCES `setec`.`event` (`id`),
  CONSTRAINT `commission_ibfk_2`
    FOREIGN KEY (`fk_id_user`)
    REFERENCES `setec`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `setec`.`speaker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setec`.`speaker` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `company` VARCHAR(100) NULL DEFAULT NULL,
  `position` VARCHAR(100) NULL DEFAULT NULL,
  `bio` TEXT NULL DEFAULT NULL,
  `approved` TINYINT(1) NULL DEFAULT NULL,
  `fk_id_user` BIGINT NOT NULL,
  `fk_Admin_Uid_Approved` VARCHAR(255) NULL DEFAULT NULL,
  `dateFatecConclusion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_user` (`fk_id_user` ASC) VISIBLE,
  INDEX `fk_Admin_Uid_Approved` (`fk_Admin_Uid_Approved` ASC) VISIBLE,
  CONSTRAINT `speaker_ibfk_1`
    FOREIGN KEY (`fk_id_user`)
    REFERENCES `setec`.`user` (`id`),
  CONSTRAINT `speaker_ibfk_2`
    FOREIGN KEY (`fk_Admin_Uid_Approved`)
    REFERENCES `setec`.`user` (`uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `setec`.`social_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setec`.`social_media` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `platform` VARCHAR(100) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `fk_Speaker` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Speaker` (`fk_Speaker` ASC) VISIBLE,
  CONSTRAINT `social_media_ibfk_1`
    FOREIGN KEY (`fk_Speaker`)
    REFERENCES `setec`.`speaker` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `setec`.`speaker_activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setec`.`speaker_activity` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `fk_Activity` BIGINT NOT NULL,
  `fk_Speaker` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Activity_id_activity` (`fk_Activity` ASC) VISIBLE,
  INDEX `fk_Speaker_id_speaker` (`fk_Speaker` ASC) VISIBLE,
  CONSTRAINT `speaker_activity_ibfk_1`
    FOREIGN KEY (`fk_Activity`)
    REFERENCES `setec`.`activity` (`id`),
  CONSTRAINT `speaker_activity_ibfk_2`
    FOREIGN KEY (`fk_Speaker`)
    REFERENCES `setec`.`speaker` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `setec`.`sponsor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setec`.`sponsor` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `fk_event_commission` BIGINT NOT NULL,
  `isLegalEntity` TINYINT(1) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `sponsorshipValue` DECIMAL(10,2) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `obs` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_commission/sponsor_idx` (`fk_event_commission` ASC) VISIBLE,
  CONSTRAINT `id_commission/sponsor`
    FOREIGN KEY (`fk_event_commission`)
    REFERENCES `setec`.`commission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;