CREATE TABLE `users` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`name` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`ra` VARCHAR(13) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`Relationship` ENUM('EXALUNO','ALUNO','PROFESSOR','COORDENADOR','SEMRELACAO') NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`Role` ENUM('ADMIN','STUDENT','COMMISSION','SPEAKER') NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`uid` VARCHAR(36) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `UK_6dotkott2kjsp8vw4d0m25fb7` (`email`) USING BTREE,
	UNIQUE INDEX `UK_kb3lfe1v013iq1y3j9i79kug6` (`ra`) USING BTREE,
	UNIQUE INDEX `UK_efqukogbk7i0poucwoy2qie74` (`uid`) USING BTREE
)